services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 --workers 6 pygoat.wsgi
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - migration
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE  # Required for binding to port 8000
  migration:
    image: pygoat/pygoat:latest
    command: python manage.py migrate --noinput
    volumes:
      - .:/app
    cap_drop:
      - ALL
    cap_add:
      - CHOWN  # Required for file operations during migration